resources:
- repo: self

pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: NodeTool@0
  displayName: 'Use specific node version'
  inputs:
    versionSpec: '8.12.0'

- script: |
    npm install -g npm@6.4.1
    npm update
    npm install
    npm install -g typescript
    npm install -g gulp-cli
    gulp compile-and-build
    gulp create-env
    gulp server & gulp server-test && npm run client-test && gulp client-e2e-test && gulp server-kill

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: drop'
